# fly.toml app configuration file generated for markitdown-api on 2024-12-16T23:32:19+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'markitdown-api'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  MAX_UPLOAD_SIZE = '63000000'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 20

  [[http_service.checks]]
    interval = '2m0s'
    timeout = '10s'
    grace_period = '3m0s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1GB'
  cpu_kind = 'shared'
  cpus = 1
